export enum CreateTransactionActionType {
  CREATE_TRANSACTIONS = 'CREATE_TRANSACTIONS',
  CREATE_TRANSACTIONS_SUCCESS = 'CREATE_TRANSACTIONS_SUCCESS',
  CREATE_TRANSACTIONS_ERROR = 'CREATE_TRANSACTIONS_ERROR',
}
