export enum DeleteTransactionActionType {
  DELETE_TRANSACTIONS = 'DELETE_TRANSACTIONS',
  DELETE_TRANSACTIONS_SUCCESS = 'DELETE_TRANSACTIONS_SUCCESS',
  DELETE_TRANSACTIONS_ERROR = 'DELETE_TRANSACTIONS_ERROR',
}
